# bacon configuration for token editor
# Run with: bacon [job]
# See https://dystroy.org/bacon/

default_job = "check"

[jobs.check]
command = ["cargo", "check", "--all-targets"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--all-features", "--", "-D", "warnings"]
need_stdout = false

[jobs.test]
command = ["cargo", "test"]
need_stdout = true

[jobs.nextest]
command = ["cargo", "nextest", "run"]
need_stdout = true

[jobs.bench]
command = ["cargo", "bench"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--no-deps"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--release", "--", "test_files/sample_code.rs"]
need_stdout = true
background = true

[keybindings]
c = "job:clippy"
t = "job:test"
n = "job:nextest"
b = "job:bench"
d = "job:doc"
r = "job:run"
